image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Flutter
    init: |
      export PATH="$PATH:/home/gitpod/flutter/bin"
      flutter doctor
      flutter pub get

vscode:
  extensions:
    - dart-code.flutter
